application:
  name: "Aplicação Genérica"
  class: "default"
  icon: "📱"
  
categories:
  - name: "Atalhos Comuns"
    keybindings:
      - key: "Ctrl+C"
        action: "Copiar"
      - key: "Ctrl+V"
        action: "Colar"
      - key: "Ctrl+X"
        action: "Recortar"
      - key: "Ctrl+A"
        action: "Selecionar tudo"
      - key: "Ctrl+Z"
        action: "Desfazer"
      - key: "Ctrl+Y / Ctrl+Shift+Z"
        action: "Refazer"
      - key: "Ctrl+S"
        action: "Salvar"
      - key: "Ctrl+O"
        action: "Abrir"
      - key: "Ctrl+N"
        action: "Novo"
      - key: "Ctrl+W"
        action: "Fechar"
      - key: "Ctrl+Q"
        action: "Sair da aplicação"
        
  - name: "Navegação"
    keybindings:
      - key: "Tab"
        action: "Próximo campo/elemento"
      - key: "Shift+Tab"
        action: "Campo/elemento anterior"
      - key: "Page Up/Down"
        action: "Scroll página"
      - key: "Home/End"
        action: "Início/Fim do documento"
      - key: "Ctrl+Home/End"
        action: "Início/Fim absoluto"
      - key: "Arrow Keys"
        action: "Navegação direcional"
        
  - name: "Busca"
    keybindings:
      - key: "Ctrl+F"
        action: "Buscar"
      - key: "F3 / Ctrl+G"
        action: "Próxima ocorrência"
      - key: "Shift+F3"
        action: "Ocorrência anterior"
      - key: "Ctrl+H"
        action: "Substituir"
      - key: "Esc"
        action: "Cancelar busca"
        
  - name: "Janelas"
    keybindings:
      - key: "F11"
        action: "Tela cheia"
      - key: "Alt+F4"
        action: "Fechar janela"
      - key: "Ctrl+Tab"
        action: "Próxima aba/documento"
      - key: "Ctrl+Shift+Tab"
        action: "Aba/documento anterior"
        
  - name: "Ajuda"
    keybindings:
      - key: "F1"
        action: "Ajuda"
      - key: "Ctrl+?"
        action: "Atalhos de teclado"